// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6uc-rama1kNq83ndet4NCDxKkXM_nTM',
    appId: '1:113150692528:web:c19714afd4b5d938f2ff75',
    messagingSenderId: '113150692528',
    projectId: 'alta-book',
    authDomain: 'alta-book.firebaseapp.com',
    storageBucket: 'alta-book.appspot.com',
    measurementId: 'G-STV889GN64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCww8lr6TGTQZRTB1Ge8kH6sajuOig-u3k',
    appId: '1:113150692528:android:f3ee3b71be34b86ff2ff75',
    messagingSenderId: '113150692528',
    projectId: 'alta-book',
    storageBucket: 'alta-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfJOKb2FsxNbVyIriXvlV2EmtId1yC2g',
    appId: '1:113150692528:ios:5711815aff7b7c61f2ff75',
    messagingSenderId: '113150692528',
    projectId: 'alta-book',
    storageBucket: 'alta-book.appspot.com',
    iosBundleId: 'com.example.olib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfJOKb2FsxNbVyIriXvlV2EmtId1yC2g',
    appId: '1:113150692528:ios:c2c14b82ec104fd0f2ff75',
    messagingSenderId: '113150692528',
    projectId: 'alta-book',
    storageBucket: 'alta-book.appspot.com',
    iosBundleId: 'com.example.olib.RunnerTests',
  );
}
